2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Configure stats pid to 12040
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ekaushik\.config\wandb\settings
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Loading settings from c:\Users\ekaushik\Desktop\MLOps\Assignment 1\wandb\settings
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'mode': 'dryrun'}
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\ekaushik\Desktop\MLOps\Assignment 1\wandb\offline-run-20240403_175633-pa21rqbl\logs\debug.log
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\ekaushik\Desktop\MLOps\Assignment 1\wandb\offline-run-20240403_175633-pa21rqbl\logs\debug-internal.log
2024-04-03 17:56:33,578 INFO    MainThread:12040 [wandb_init.py:init():567] calling init triggers
2024-04-03 17:56:33,589 INFO    MainThread:12040 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-03 17:56:33,589 INFO    MainThread:12040 [wandb_init.py:init():592] re-initializing run, found existing run on stack: mr3lt0be
2024-04-03 17:56:33,596 INFO    MainThread:12040 [wandb_run.py:_finish():2052] finishing run mr3lt0be
2024-04-03 17:56:33,598 ERROR   MainThread:12040 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-03 17:56:33,598 INFO    MainThread:12040 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-03 17:56:33,598 INFO    MainThread:12040 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-04-03 17:56:33,598 INFO    MainThread:12040 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-03 17:56:33,598 INFO    MainThread:12040 [wandb_run.py:_restore():2275] restore
2024-04-03 17:56:33,598 INFO    MainThread:12040 [wandb_run.py:_restore():2281] restore done
2024-04-03 17:56:34,662 INFO    MainThread:12040 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-03 17:56:34,662 INFO    MainThread:12040 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-04-03 17:56:36,681 INFO    MainThread:12040 [wandb_init.py:init():617] starting backend
2024-04-03 17:56:36,681 INFO    MainThread:12040 [wandb_init.py:init():621] setting up manager
2024-04-03 17:56:36,684 INFO    MainThread:12040 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-03 17:56:36,685 INFO    MainThread:12040 [wandb_init.py:init():629] backend started and connected
2024-04-03 17:56:36,692 INFO    MainThread:12040 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-03 17:56:36,692 INFO    MainThread:12040 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-03 17:56:36,692 INFO    MainThread:12040 [wandb_init.py:init():721] updated telemetry
2024-04-03 17:56:36,694 INFO    MainThread:12040 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-04-03 17:56:36,709 INFO    MainThread:12040 [wandb_init.py:init():805] starting run threads in backend
2024-04-03 17:56:37,433 INFO    MainThread:12040 [wandb_run.py:_console_start():2323] atexit reg
2024-04-03 17:56:37,436 INFO    MainThread:12040 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-04-03 17:56:37,436 INFO    MainThread:12040 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-04-03 17:56:37,436 INFO    MainThread:12040 [wandb_run.py:_redirect():2268] Redirects installed.
2024-04-03 17:56:37,436 INFO    MainThread:12040 [wandb_init.py:init():848] run started, returning control to user process
2024-04-03 17:58:14,656 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-03 17:58:14,657 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Configure stats pid to 12040
2024-04-03 17:58:14,657 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ekaushik\.config\wandb\settings
2024-04-03 17:58:14,657 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Loading settings from c:\Users\ekaushik\Desktop\MLOps\Assignment 1\wandb\settings
2024-04-03 17:58:14,659 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'mode': 'dryrun'}
2024-04-03 17:58:14,660 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 17:58:14,660 INFO    MainThread:12040 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-03 17:58:14,660 INFO    MainThread:12040 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\ekaushik\Desktop\MLOps\Assignment 1\wandb\offline-run-20240403_175814-qjmrryhm\logs\debug.log
2024-04-03 17:58:14,661 INFO    MainThread:12040 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\ekaushik\Desktop\MLOps\Assignment 1\wandb\offline-run-20240403_175814-qjmrryhm\logs\debug-internal.log
2024-04-03 17:58:14,661 INFO    MainThread:12040 [wandb_init.py:_jupyter_setup():473] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001C1AF600810>
2024-04-03 17:58:14,661 INFO    MainThread:12040 [wandb_init.py:init():567] calling init triggers
2024-04-03 17:58:14,661 INFO    MainThread:12040 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-03 17:58:14,662 INFO    MainThread:12040 [wandb_init.py:init():592] re-initializing run, found existing run on stack: pa21rqbl
2024-04-03 17:58:14,664 INFO    MainThread:12040 [wandb_run.py:_finish():2052] finishing run pa21rqbl
2024-04-03 17:58:14,664 INFO    MainThread:12040 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-03 17:58:14,664 INFO    MainThread:12040 [wandb_run.py:_restore():2275] restore
2024-04-03 17:58:14,664 INFO    MainThread:12040 [wandb_run.py:_restore():2281] restore done
2024-04-03 17:58:15,714 INFO    MainThread:12040 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-03 17:58:15,714 INFO    MainThread:12040 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
